import {cleanup, render, screen} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {afterEach, beforeEach, describe, expect, it, vi} from "vitest";

import type {Listing} from "@/lib/sidecar-api";

const {
  approveListingForExportMock,
  enqueueGenerateListingMock,
  saveListingEditsMock,
  saveListingImageUrlsMock,
  updateListingStatusMock,
} = vi.hoisted(() => ({
  approveListingForExportMock: vi.fn(),
  enqueueGenerateListingMock: vi.fn(),
  saveListingEditsMock: vi.fn(),
  saveListingImageUrlsMock: vi.fn(),
  updateListingStatusMock: vi.fn(),
}));

vi.mock("@/app/listing-generate-actions", () => ({
  enqueueGenerateListing: enqueueGenerateListingMock,
}));

vi.mock("@/app/listing-actions", () => ({
  saveListingEdits: saveListingEditsMock,
}));

vi.mock("@/app/listing-image-url-actions", () => ({
  saveListingImageUrls: saveListingImageUrlsMock,
}));

vi.mock("@/app/listing-status-actions", () => ({
  updateListingStatus: updateListingStatusMock,
}));

vi.mock("@/app/listing-approve-export-actions", () => ({
  approveListingForExport: approveListingForExportMock,
}));

import {ListingsTableEditable} from "@/app/listings-table-editable";

function buildListing(
  listingId: string,
  status: Listing["status"],
  updatedAt: string,
  overrides: Partial<Listing> = {},
): Listing {
  return {
    approved_for_export_at: null,
    capture_mode: null,
    category_id: null,
    condition_id: null,
    condition_notes: null,
    created_at: "2026-05-20T00:00:00.000Z",
    description: null,
    ebay_listing_id: null,
    ebay_listing_status: null,
    ebay_listing_url: null,
    ebay_offer_id: null,
    ese_eligible: null,
    estimated_weight_oz: null,
    exported_at: null,
    handling_days: null,
    id: `${listingId}-row-id`,
    image_urls: [],
    item_specifics: {},
    last_error_at: null,
    last_error_code: null,
    last_error_message: null,
    listing_id: listingId,
    listing_type: null,
    merchant_location_key: null,
    package_type: null,
    price: null,
    r2_delete_after: null,
    r2_deleted_at: null,
    r2_object_keys: [],
    r2_retention_policy: null,
    seller_hints: null,
    shipping_profile: null,
    sku: null,
    sold_at: null,
    status,
    sub_status: "idle",
    title: null,
    updated_at: updatedAt,
    ...overrides,
  };
}

describe("ListingsTableEditable reconciliation", () => {
  afterEach(() => {
    cleanup();
  });

  beforeEach(() => {
    approveListingForExportMock.mockReset();
    enqueueGenerateListingMock.mockReset();
    saveListingEditsMock.mockReset();
    saveListingImageUrlsMock.mockReset();
    updateListingStatusMock.mockReset();
  });

  it("reconciles an open listing to fresh workflow data on rerender", async () => {
    const user = userEvent.setup();
    const {rerender} = render(
      <ListingsTableEditable
        listings={[buildListing("LIST-GEN", "generating", "2026-05-20T00:00:00.000Z")]}
      />,
    );

    await user.click(screen.getByRole("button", {name: "View"}));

    expect(
      screen.getByText(/AI generation is in progress\. Listing edits are locked/i),
    ).not.toBeNull();

    rerender(
      <ListingsTableEditable
        listings={[
          buildListing("LIST-GEN", "needs_review", "2026-05-20T01:00:00.000Z", {
            description: "Generated by Gemini.",
            item_specifics: {brand: "Topps", year: 2024},
            sub_status: "review_pending",
            title: "Gemini draft title",
          }),
        ]}
      />,
    );

    expect(
      screen.getByText(
        /AI draft ready for review\. Confirm or edit the generated fields before approving for export\./i,
      ),
    ).not.toBeNull();
    expect((screen.getByLabelText("Title") as HTMLInputElement).value).toBe(
      "Gemini draft title",
    );
    expect((screen.getByLabelText("Description") as HTMLTextAreaElement).value).toBe(
      "Generated by Gemini.",
    );
    expect(
      (screen.getByLabelText("Item specifics (JSON)") as HTMLTextAreaElement)
        .value,
    ).toBe(JSON.stringify({brand: "Topps", year: 2024}, null, 2));
  });

  it("closes an open listing when refreshed data no longer includes it", async () => {
    const user = userEvent.setup();
    const {rerender} = render(
      <ListingsTableEditable
        listings={[
          buildListing("LIST-GEN", "generating", "2026-05-20T00:00:00.000Z"),
          buildListing("LIST-OTHER", "needs_review", "2026-05-20T01:00:00.000Z"),
        ]}
      />,
    );

    await user.click(screen.getByRole("button", {name: "View"}));
    expect(screen.getByText("Edit listing")).not.toBeNull();

    rerender(
      <ListingsTableEditable
        listings={[buildListing("LIST-OTHER", "needs_review", "2026-05-20T01:00:00.000Z")]}
      />,
    );

    expect(screen.queryByText("Edit listing")).toBeNull();
  });
});
