import {cleanup, render, screen, waitFor} from "@testing-library/react";
import {fireEvent} from "@testing-library/react";
import {afterEach, beforeEach, describe, expect, it, vi} from "vitest";

import type {Listing} from "@/lib/sidecar-api";

const fetchMock = vi.fn();
const {
  approveListingForExportMock,
  enqueueGenerateListingMock,
  saveListingEditsMock,
  saveListingImageUrlsMock,
  updateListingStatusMock,
} = vi.hoisted(() => ({
  approveListingForExportMock: vi.fn(),
  enqueueGenerateListingMock: vi.fn(),
  saveListingEditsMock: vi.fn(),
  saveListingImageUrlsMock: vi.fn(),
  updateListingStatusMock: vi.fn(),
}));

vi.mock("@/app/listing-generate-actions", () => ({
  enqueueGenerateListing: enqueueGenerateListingMock,
}));

vi.mock("@/app/listing-actions", () => ({
  saveListingEdits: saveListingEditsMock,
}));

vi.mock("@/app/listing-image-url-actions", () => ({
  saveListingImageUrls: saveListingImageUrlsMock,
}));

vi.mock("@/app/listing-status-actions", () => ({
  updateListingStatus: updateListingStatusMock,
}));

vi.mock("@/app/listing-approve-export-actions", () => ({
  approveListingForExport: approveListingForExportMock,
}));

import {ListingsRealtime} from "@/app/listings-realtime";

function buildListing(overrides: Partial<Listing> = {}): Listing {
  return {
    approved_for_export_at: null,
    capture_mode: null,
    category_id: null,
    condition_id: null,
    condition_notes: null,
    created_at: "2026-05-20T00:00:00.000Z",
    description: null,
    ebay_listing_id: null,
    ebay_listing_status: null,
    ebay_listing_url: null,
    ebay_offer_id: null,
    ese_eligible: null,
    estimated_weight_oz: null,
    exported_at: null,
    handling_days: null,
    id: "listing-row-id",
    image_urls: ["https://example.com/image.jpg"],
    item_specifics: {},
    last_error_at: null,
    last_error_code: null,
    last_error_message: null,
    listing_id: "LIST-001",
    listing_type: null,
    merchant_location_key: null,
    package_type: null,
    price: null,
    r2_delete_after: null,
    r2_deleted_at: null,
    r2_object_keys: [],
    r2_retention_policy: null,
    seller_hints: null,
    shipping_profile: null,
    sku: null,
    sold_at: null,
    status: "assets_ready",
    sub_status: "ready_to_generate",
    title: null,
    updated_at: "2026-05-20T00:00:00.000Z",
    ...overrides,
  };
}

function jsonResponse(listings: Listing[]) {
  return new Response(JSON.stringify({listings}), {
    headers: {"content-type": "application/json"},
    status: 200,
  });
}

describe("ListingsRealtime", () => {
  beforeEach(() => {
    fetchMock.mockReset();
    approveListingForExportMock.mockReset();
    enqueueGenerateListingMock.mockReset();
    saveListingEditsMock.mockReset();
    saveListingImageUrlsMock.mockReset();
    updateListingStatusMock.mockReset();
    vi.stubGlobal("fetch", fetchMock);
  });

  afterEach(() => {
    cleanup();
    vi.unstubAllGlobals();
  });

  it("updates visible status and generated fields from polled refreshes", async () => {
    let refreshCount = 0;
    fetchMock.mockImplementation(async () => {
      refreshCount += 1;

      if (refreshCount === 1) {
        return jsonResponse([buildListing()]);
      }

      if (refreshCount === 2) {
        return jsonResponse([
          buildListing({
            description: "Backend is now generating the draft.",
            status: "generating",
            title: "Draft title",
            updated_at: "2026-05-20T01:00:00.000Z",
          }),
        ]);
      }

      return jsonResponse([
        buildListing({
          description: "Generated by Gemini.",
          item_specifics: {brand: "Topps", year: 2024},
          status: "needs_review",
          sub_status: "review_pending",
          title: "Gemini draft title",
          updated_at: "2026-05-20T02:00:00.000Z",
        }),
      ]);
    });

    render(
      <ListingsRealtime
        initialListings={[buildListing()]}
        refreshIntervalMs={20}
      />,
    );

    await waitFor(() => expect(refreshCount).toBeGreaterThanOrEqual(1));

    await waitFor(() => expect(refreshCount).toBeGreaterThanOrEqual(2));
    await waitFor(() => {
      expect(screen.getByRole("button", {name: "View"})).not.toBeNull();
    });

    expect(
      screen.queryByText(
        "AI generation is in progress. Listing edits are locked until the draft is ready for review.",
      ),
    ).toBeNull();

    await waitFor(() => expect(refreshCount).toBeGreaterThanOrEqual(3));
    await waitFor(() => {
      expect(screen.getByRole("button", {name: "Review"})).not.toBeNull();
    });

    fireEvent.click(screen.getByRole("button", {name: "Review"}));

    expect((screen.getByLabelText("Title") as HTMLInputElement).value).toBe(
      "Gemini draft title",
    );
    expect((screen.getByLabelText("Description") as HTMLTextAreaElement).value).toBe(
      "Generated by Gemini.",
    );
    expect(
      (screen.getByLabelText("Item specifics (JSON)") as HTMLTextAreaElement)
        .value,
    ).toBe(JSON.stringify({brand: "Topps", year: 2024}, null, 2));
  });

  it("stops refreshing when unmounted", async () => {
    let refreshCount = 0;
    fetchMock.mockImplementation(async () => {
      refreshCount += 1;
      return jsonResponse([buildListing()]);
    });

    const {unmount} = render(
      <ListingsRealtime
        initialListings={[buildListing()]}
        refreshIntervalMs={20}
      />,
    );

    await waitFor(() => expect(refreshCount).toBeGreaterThanOrEqual(2));

    unmount();

    const countAfterUnmount = refreshCount;
    await new Promise((resolve) => setTimeout(resolve, 100));

    expect(refreshCount).toBe(countAfterUnmount);
  });
});
